version: "3"

services:
    loki:
        image: grafana/loki:master
        command: -config.file=/etc/loki/local-config.yaml
        networks:
            - grafana-loki
            - promtail-loki

    promtail:
        depends_on:
            - loki
        image: grafana/promtail:master
        volumes:
            - /var/log:/var/log
        command: -config.file=/etc/promtail/docker-config.yaml
        networks:
            - promtail-loki

    cadvisor:
        image: google/cadvisor:v0.33.0
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:ro
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
            - /dev/disk/:/dev/disk:ro
        networks:
            - prometheus-cadvisor

    prometheus:
        image: prom/prometheus:v2.7.1
        ports:
            - "9090:9090"
        volumes:
            - ./prometheus:/app.cfg
        networks:
            - world
            - prometheus-cadvisor
            - grafana-prometheus
        command: >-
            --config.file=/app.cfg/prometheus.yml
            --storage.tsdb.path=/prometheus
            --web.console.libraries=/usr/share/prometheus/console_libraries
            --web.console.templates=/usr/share/prometheus/consoles

    grafana:
        depends_on:
            - loki
        image: grafana/grafana:6.0.0
        ports:
            - "3000:3000"
        environment:
            GF_SECURITY_ADMIN_USER: admin
            GF_SECURITY_ADMIN_PASSWORD: test
            GF_PATHS_PROVISIONING: '/app.cfg/provisioning'
        volumes:
            - ./grafana:/app.cfg
        networks:
            - world
            - grafana-loki
            - grafana-prometheus

networks:
    world:
    promtail-loki:
        internal: true
    grafana-loki:
        internal: true
    grafana-prometheus:
        internal: true
    prometheus-cadvisor:
        internal: true
